# Generated by Django 4.1 on 2023-07-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cod_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_venta',
            fields=[
                ('cod_tipoventa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cod_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('cod_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('cod_venta', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.DateField()),
                ('cod_tipoventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tipo_venta')),
                ('cod_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('cod_dventa', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('cod_producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('cod_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.venta')),
            ],
        ),
    ]
