# Generated by Django 4.1 on 2023-07-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_venta_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_venta',
            name='cod_dventa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
